[versions]
android-compileSdk = "36"
android-minSdk = "26"
android-ndk = "29.0.14206865"
library-version = "1.2.3"
agp = "8.13.0"
kotlin = "2.2.21"

# --- Libraries ---
resource-loader = "2.1.0"
slf4j = "2.0.17"
commons-codec = "1.19.0"
bip39 = "1.0.9"
json-kotlin-schema = "0.57"
serialization = "1.9.0"
jackson = "2.20.1"
msgpack = "0.9.10"
nmcp = "1.2.0"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
maven-publish = { id = "maven-publish" }
signing = { id = "signing" }

[libraries]
# Core
resource-loader = { module = "com.goterl:resource-loader", version.ref = "resource-loader" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }

# Crypto / wallet dependencies
bip39 = { module = "cash.z.ecc.android:kotlin-bip39", version.ref = "bip39" }

# JSON / serialization
json-kotlin-schema = { module = "net.pwall.json:json-kotlin-schema", version.ref = "json-kotlin-schema" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }

# Jackson / message formats
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-dataformat-msgpack = { module = "org.msgpack:jackson-dataformat-msgpack", version.ref = "msgpack" }
jackson-dataformat-cbor = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-cbor", version.ref = "jackson" }